package pe.edu.grupo3_asignacion1.services

import pe.edu.grupo3_asignacion1.models.Photo


class ImageService {
    companion object {
        fun fetchAll(): List<Photo> {
            return listOf(
                Photo(1,"https://images.pexels.com/photos/16407235/pexels-photo-16407235.jpeg",1,"image1"),
                Photo(2,"https://images.pexels.com/photos/15561915/pexels-photo-15561915.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",1,"image2"),
                Photo(3,"https://images.pexels.com/photos/14245756/pexels-photo-14245756.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",1,"image3"),
                Photo(4,"https://images.pexels.com/photos/16041156/pexels-photo-16041156.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",1,"image4"),
                Photo(5,"https://images.pexels.com/photos/11977484/pexels-photo-11977484.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",1,"image5"),
                Photo(6,"https://images.pexels.com/photos/15549494/pexels-photo-15549494.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",1,"image6"),
                Photo(7,"https://images.pexels.com/photos/14155717/pexels-photo-14155717.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",1,"image7"),
                Photo(8,"https://images.pexels.com/photos/15844493/pexels-photo-15844493.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",1,"image8"),
                Photo(9,"https://images.pexels.com/photos/4738517/pexels-photo-4738517.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",1,"image9"),
                Photo(0, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/427.png", 6,"text"),
                Photo(10, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/596.png", 2,"text"),
                Photo(11, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/720.png", 8,"text"),
                Photo(13, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/15.png", 10,"text"),
                Photo(14, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/292.png", 3,"text"),
                Photo(15, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/233.png", 2,"text"),
                Photo(16, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/491.png", 8,"text"),
                Photo(17, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/704.png", 3,"text"),
                Photo(18, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/271.png", 8,"text"),
                Photo(19, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/18.png", 9,"text"),
                Photo(20, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/154.png", 10,"text"),
                Photo(21, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/282.png", 10,"text"),
                Photo(22, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/232.png", 8,"text"),
                Photo(23, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/661.png", 8,"text"),
                Photo(24, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/192.png", 3,"text"),
                Photo(25, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/176.png", 5,"text"),
                Photo(26, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/461.png", 5,"text"),
                Photo(27, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/197.png", 5,"text"),
                Photo(28, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/203.png", 3,"text"),
                Photo(29, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/476.png", 6,"text"),
                Photo(30, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/365.png", 2,"text"),
                Photo(31, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/191.png", 7,"text"),
                Photo(32, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/751.png", 5,"text"),
                Photo(33, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/790.png", 4,"text"),
                Photo(34, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/35.png", 6,"text"),
                Photo(35, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/577.png", 8,"text"),
                Photo(36, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/122.png", 6,"text"),
                Photo(38, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/496.png", 3,"text"),
                Photo(40, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/747.png", 4,"text"),
                Photo(41, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/185.png", 9,"text"),
                Photo(42, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/394.png", 2,"text"),
                Photo(43, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/71.png", 4,"text"),
                Photo(44, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/162.png", 8,"text"),
                Photo(45, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/660.png", 3,"text"),
                Photo(46, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/122.png", 10,"text"),
                Photo(47, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/559.png", 10,"text"),
                Photo(48, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/703.png", 10,"text"),
                Photo(49, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/636.png", 8,"text"),
                Photo(50, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/792.png", 10,"text"),
                Photo(51, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/548.png", 5,"text"),
                Photo(52, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/204.png", 3,"text"),
                Photo(53, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/335.png", 5,"text"),
                Photo(55, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/320.png", 3,"text"),
                Photo(56, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/448.png", 3,"text"),
                Photo(57, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/661.png", 4,"text"),
                Photo(59, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/532.png", 2,"text"),
                Photo(60, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/258.png", 8,"text"),
                Photo(61, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/46.png", 5,"text"),
                Photo(62, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/465.png", 10,"text"),
                Photo(63, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/227.png", 3,"text"),
                Photo(64, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/608.png", 3,"text"),
                Photo(65, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/321.png", 6,"text"),
                Photo(66, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/140.png", 2,"text"),
                Photo(67, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/610.png", 7,"text"),
                Photo(68, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/612.png", 9,"text"),
                Photo(69, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/750.png", 5,"text"),
                Photo(70, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/377.png", 9,"text"),
                Photo(72, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/246.png", 7,"text"),
                Photo(73, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/796.png", 7,"text"),
                Photo(74, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/309.png", 5,"text"),
                Photo(75, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/432.png", 2,"text"),
                Photo(76, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/24.png", 10,"text"),
                Photo(77, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/633.png", 9,"text"),
                Photo(78, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/655.png", 9,"text"),
                Photo(79, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/648.png", 10,"text"),
                Photo(80, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/785.png", 7,"text"),
                Photo(81, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/515.png", 9,"text"),
                Photo(82, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/411.png", 2,"text"),
                Photo(83, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/686.png", 2,"text"),
                Photo(84, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/710.png", 5,"text"),
                Photo(85, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/584.png", 6,"text"),
                Photo(87, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/249.png", 8,"text"),
                Photo(88, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/302.png", 4,"text"),
                Photo(89, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/445.png", 2,"text"),
                Photo(90, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/66.png", 7,"text"),
                Photo(91, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/295.png", 7,"text"),
                Photo(92, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/94.png", 5,"text"),
                Photo(93, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/189.png", 7,"text"),
                Photo(94, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/26.png", 3,"text"),
                Photo(95, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/190.png", 3,"text"),
                Photo(96, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/471.png", 4,"text"),
                Photo(97, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/636.png", 9,"text"),
                Photo(98, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/304.png", 10,"text"),
                Photo(99, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/442.png", 4,"text"),
                Photo(101, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/632.png", 7,"text"),
                Photo(102, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/680.png", 2,"text"),
                Photo(103, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/375.png", 5,"text"),
                Photo(104, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/261.png", 8,"text"),
                Photo(105, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/196.png", 10,"text"),
                Photo(106, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/3.png", 4,"text"),
                Photo(107, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/444.png", 4,"text"),
                Photo(108, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/299.png", 4,"text"),
                Photo(109, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/403.png", 6,"text"),
                Photo(110, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/268.png", 7,"text"),
                Photo(111, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/173.png", 7,"image"),
                Photo(113, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/76.png", 2,"image"),
                Photo(114, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/602.png", 7,"image"),
                Photo(115, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/253.png", 5,"image"),
                Photo(116, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/573.png", 4,"image"),
                Photo(117, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/470.png", 9,"image"),
                Photo(118, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/692.png", 10,"image"),
                Photo(119, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/715.png", 8,"image"),
                Photo(120, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/376.png", 8,"image"),
                Photo(121, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/514.png", 10,"image"),
                Photo(122, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/794.png", 2,"image"),
                Photo(123, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/116.png", 2,"image"),
                Photo(124, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/382.png", 4,"image"),
                Photo(126, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/67.png", 10,"image"),
                Photo(127, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/393.png", 9,"image"),
                Photo(128, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/634.png", 8,"image"),
                Photo(129, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/61.png", 3,"image"),
                Photo(130, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/180.png", 6,"image"),
                Photo(131, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/639.png", 8,"image"),
                Photo(132, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/225.png", 2,"image"),
                Photo(133, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/225.png", 9,"image"),
                Photo(134, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/653.png", 10,"image"),
                Photo(135, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/187.png", 2,"image"),
                Photo(136, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/758.png", 9,"image"),
                Photo(137, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/259.png", 7,"image"),
                Photo(138, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/382.png", 8,"image"),
                Photo(139, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/563.png", 7,"image"),
                Photo(140, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/91.png", 6,"image"),
                Photo(141, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/719.png", 7,"image"),
                Photo(143, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/778.png", 10,"image"),
                Photo(144, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/713.png", 5,"image"),
                Photo(145, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/355.png", 4,"image"),
                Photo(147, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/262.png", 10,"image"),
                Photo(148, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/522.png", 9,"image"),
                Photo(149, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/3.png", 3,"image"),
                Photo(150, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/23.png", 2,"image"),
                Photo(152, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/216.png", 2,"image"),
                Photo(153, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/524.png", 4,"image"),
                Photo(154, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/691.png", 3,"image"),
                Photo(155, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/13.png", 2,"image"),
                Photo(156, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/398.png", 2,"image"),
                Photo(157, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/275.png", 4,"image"),
                Photo(159, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/792.png", 10,"image"),
                Photo(160, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/488.png", 7,"image"),
                Photo(161, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/233.png", 2,"image"),
                Photo(162, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/502.png", 5,"image"),
                Photo(163, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/512.png", 9,"image"),
                Photo(166, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/176.png", 10,"image"),
                Photo(167, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/482.png", 7,"image"),
                Photo(169, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/252.png", 7,"image"),
                Photo(170, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/600.png", 4,"image"),
                Photo(171, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/246.png", 10,"image"),
                Photo(172, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/489.png", 6,"image"),
                Photo(173, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/164.png", 6,"image"),
                Photo(175, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/214.png", 3,"image"),
                Photo(176, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/770.png", 5,"image"),
                Photo(177, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/32.png", 10,"image"),
                Photo(178, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/507.png", 9,"image"),
                Photo(179, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/607.png", 2,"image"),
                Photo(180, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/631.png", 5,"image"),
                Photo(181, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/572.png", 5,"image"),
                Photo(182, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/796.png", 2,"image"),
                Photo(183, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/169.png", 3,"image"),
                Photo(184, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/131.png", 6,"image"),
                Photo(185, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/750.png", 5,"image"),
                Photo(186, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/726.png", 5,"image"),
                Photo(187, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/574.png", 3,"image"),
                Photo(188, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/656.png", 3,"image"),
                Photo(189, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/784.png", 10,"image"),
                Photo(191, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/85.png", 10,"image"),
                Photo(192, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/404.png", 5,"image"),
                Photo(193, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/273.png", 2,"image"),
                Photo(194, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/774.png", 5,"image"),
                Photo(195, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/620.png", 7,"image"),
                Photo(196, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/58.png", 3,"image"),
                Photo(197, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/514.png", 8,"image"),
                Photo(198, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/408.png", 3,"image"),
                Photo(199, "https://pokefanaticos.com/pokedex/assets/images/pokemon_imagenes/251.png", 9,"image"),
            )
        }

        fun fetchByUserId(userId: Int): List<Photo>{
            val respuesta : MutableList<Photo> = arrayListOf()
            val list: List<Photo> = fetchAll()
            for(imagen in list){
                if(imagen.usuarioId == userId){
                    respuesta.add(imagen)
                }
            }
            return respuesta
        }
    }
}